project:
  name: "AI Sentinel"
  version: "1.0.0"
  description: "Multimodal Explainable System for Detecting Digital Human Rights Violations"

data:
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  cache_dir: "cache"
  datasets:
    hatexplain:
      name: "hatexplain"
      source: "huggingface"
      path: "hatexplain"
    deepfake:
      name: "deepfake_detection"
      source: "kaggle"
      path: "deepfake-detection-challenge"
    gdelt:
      name: "gdelt"
      source: "api"
      endpoint: "https://api.gdeltproject.org/api/v2/doc/doc"

models:
  nlp:
    name: "hate_speech_detector"
    base_model: "bert-base-multilingual-cased"
    num_labels: 3
    max_length: 512
    learning_rate: 2.0e-5
    epochs: 5
    batch_size: 16
    warmup_steps: 500
    weight_decay: 0.01
    
  vision:
    name: "deepfake_detector"
    base_model: "efficientnet_b0"
    num_classes: 2
    image_size: 224
    learning_rate: 1.0e-4
    epochs: 10
    batch_size: 32
    augmentation: true
    
  fusion:
    name: "multimodal_fusion"
    fusion_type: "late"
    hidden_dim: 256
    dropout: 0.3
    learning_rate: 1.0e-4

explainability:
  shap:
    enabled: true
    max_samples: 100
    background_samples: 50
  lime:
    enabled: true
    num_features: 10
    num_samples: 1000

correlation:
  gdelt:
    enabled: true
    lookback_days: 7
    min_confidence: 0.7
    event_types:
      - "PROTEST"
      - "VIOLENCE"
      - "CONFLICT"
      - "REPRESSION"

api:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  reload: false
  cors_origins:
    - "http://localhost:8501"
    - "http://localhost:3000"

dashboard:
  port: 8501
  title: "AI Sentinel - Digital Rights Monitor"
  refresh_interval: 300
  max_results: 100
  map_style: "open-street-map"

elasticsearch:
  host: "localhost"
  port: 9200
  index: "ai_sentinel"
  mappings:
    properties:
      timestamp:
        type: "date"
      content_type:
        type: "keyword"
      prediction:
        type: "keyword"
      confidence:
        type: "float"
      location:
        type: "geo_point"
      language:
        type: "keyword"
      explanation:
        type: "text"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/ai_sentinel.log"
  max_bytes: 10485760
  backup_count: 5