[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[client]
showErrorDetails = true
showSidebarNavigation = true

[logger]
level = "info"

[server]
# Increase timeout for large model inference
maxUploadSize = 200
enableCORS = true
headless = true
port = 8501